name: Run Skaffold Pipeline, Deploy to AKS and run Unguard Helm Test
on:
  pull_request:
    paths:
      - src/**
      - skaffold.yaml
      - chart/**

  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (e.g., dev, staging, prod)'
        required: true
        default: 'dev'
      run_tests:
        description: 'Run Helm tests (true/false)'
        required: false
        default: 'true'

jobs:
  test:
    runs-on: eks
    timeout-minutes: 30
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.21.0
        env:
          OTLP_PROTOCOL: HTTPS
          WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
          WORKFLOW_RUN_NAME: ${{ github.event.workflow_run.name }}
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: Authorization=Api-Token ${{ secrets.DYNATRACE_OTEL_API_TOKEN }}
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_METRICS_ENDPOINT }}
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT }}
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_LOGS_ENDPOINT }}
           
          GITHUB_DEBUG: true
          
        with:
          secrets_to_redact: '["${{ github.token }}"]'    
      - name: Checkout sources
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials (optional if EC2 has instance profile)
        run: |
             aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
             aws configure set region ${{ secrets.EKS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
            aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.EKS_REGION }}

      - name: Test kubectl access
        run: |
            kubectl get pods -A
  
      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.3

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs . --charts ./chart --validate-maintainers=false --check-version-increment=false --target-branch ${{ github.event.repository.default_branch }}

      - name: Cache Skaffold layers
        uses: actions/cache@v3
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}

      - name: Run Skaffold and Deploy to AKS
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          command: run
          skip-tests: true

      - name: Run chart-testing
        run: helm test unguard --namespace unguard --timeout 10m0s --logs
    permissions:
      actions: read        
